### ISSUE TITLE
建议添加小样本模型训练

### ISSUE THREAD

**Issue by wolf-li** [zyds/transformers-code#1]

**Comment by zyds** [comment]
@wolf-li 可否说的再具体一点呢？小样本场景还蛮多的

**Comment by wolf-li** [comment]
其实我觉得都可以，明确一个任务，实现小样本学习达到大量样本的效果。提出这个问题也是之前在工作中遇到的问题，情况就是当没有大量样本时候，网上公开语料没有符合自己的，gpt生成文本没有达到预期情况下，如何训练好一个模型。我之前做过中文文本摘要小样本训练，用苏神的 t5-pegasus 效果不错。

**Comment by zyds** [comment]
这个看情况吧，概率不大，我这边的重点还是讲清楚transformers生态如何使用，这种很专项的，推荐多看下论文~
