### ISSUE TITLE
Tuning

### ISSUE THREAD

**Issue by Shyvvon** [zyds/transformers-code#12]
RuntimeError: The expanded size of the tensor (14) must match the existing size (24) at non-singleton dimension 2.  Target sizes: [16, 14, 14].  Tensor sizes: [16, 1, 24]，为什么在推理时会报这个错误

**Comment by zyds** [comment]
有具体一些的信息嘛，例如是哪个代码

**Comment by Shyvvon** [comment]
@zyds 


prompt—tuning、p-tuning这两章，推理时报这个错误，把num_virtual_tokens设为0就不会报

**Comment by zyds** [comment]
是训练完成后直接推理的吗？还是又加载了一次？

**Comment by Shyvvon** [comment]
@zyds 
重新加载的，没有等训练完，到checkpoint-20的时候就中止，然后peft_model = PeftModel.from_pretrained(model=model, model_id="./chatbot/checkpoint-20/")。或者"Human: {}\n{}".format("考试有哪些技巧？", "")改为"下面是一段人与机器人的对话。Human: {}\n{}".format("考试有哪些技巧？", "")也不报错

**Comment by zyds** [comment]
如果是在一个jupyter里面，在执行下面这行代码之前，你需要重新初始化模型，因为model已经是一个peftmodel了，如果不重新加载原始模型，相当于你又封装了一层

`peft_model = PeftModel.from_pretrained(model=model, model_id="./chatbot/checkpoint-20/")`

**Comment by Shyvvon** [comment]
@zyds 
跟源码一样的，也会报错，而且不经过训练直接执行下面的代码也会报错，将"Human: {}\n{}".format("考试有哪些技巧？", "")改为"下面是一段人与机器人的对话。Human: {}\n{}".format("考试有哪些技巧？", "")就不会报错
`model = get_peft_model(model, config)，model.generate(**ipt, max_length=128, do_sample=True)`

**Comment by Shyvvon** [comment]
@zyds
之前在服务器上跑的，刚在本地跑了下也没报错，奇了怪了

**Comment by zyds** [comment]
大概率就是因为jupyter中模型没有重新加载导致的，可以再确认一下

**Comment by Shyvvon** [comment]
@zyds 
Prompt-Tuning原理与实战视频的15分4秒时，也没有重新加载模型，同样的代码我执行就会报错

**Comment by zyds** [comment]
@Shyvvon 我这边本地也跑了下prompt-tuning、p-tuning的代码，确实是没啥问题，可以再确认下环境，和readme中的环境对齐，或者看看是不是哪里写疏忽了
