### ISSUE TITLE
是否会添加Trainer再深入一些的案例，比如自定义Trainer等

### ISSUE THREAD

**Issue by Yimi81** [zyds/transformers-code#2]
感谢up主的教程，我想问的是未来是否有计划添加一些更深入的Trainer教程，目前的案例都只是简单的使用了Trainer,有时候我想继承它自定义一个自己的Trainer，比如自定义loss(compute_loss) ,自定义training_step来实现GAN等等，不仅仅只用在训练常规的通过from_pretrained的NLP模型。

**Comment by Yimi81** [comment]
比如我想用transformers的datasets, Trainer，重写下面这个简单的GAN代码，学完之后自己还是遇到了问题，https://github.com/eriklindernoren/PyTorch-GAN/blob/master/implementations/gan/gan.py

**Comment by zyds** [comment]
@Yimi81 未来应该会有，不过GAN这种，我可能还是会推荐自己写训练流程，涉及到很多细节控制，trainer确实就不太方便了

**Comment by Yimi81** [comment]
感谢回复，明白了
