### ISSUE TITLE
合并权重的问题

### ISSUE THREAD

**Issue by J-G-Y** [zyds/transformers-code#4]
作者您好，感谢相关视频录制分享教学，想和您请教一下Bitfit或者Lora这种LLM微调方法，可以将保存的权重和原模型合并吗（我理解为替换原模型相关权重）

**Comment by zyds** [comment]
可以的，Lora的视频里也讲到了哈~

**Comment by J-G-Y** [comment]
> 可以的，Lora的视频里也讲到了哈~

好的，我再去看看您的视频学习一下，谢谢回复
