### ISSUE TITLE
ChatGLM-6B的模型输入构建

### ISSUE THREAD

**Issue by J-G-Y** [zyds/transformers-code#5]
作者您好，您在GLM微调中使用了GLM-large-Chinese模型，通过以下语句构建了模型的输入

inputs = tokenizer(contents, max_length=384, truncation=True, padding="max_length", return_tensors="pt")
inputs = tokenizer.build_inputs_for_generation(inputs, targets=exmaples['title'], padding=True, max_gen_length=64)

想和您请教一下，如果模型换成ChatGLM-6B，第二行代码应该做什么样的改变，我没有找到相关的自定义方法

**Comment by zyds** [comment]
@J-G-Y 可以看下Chatglm官方的微调代码
